name: 02 - Workflow Events

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            # github context
            - name: Show the trigger
              run: echo "ive been triggered by a(n) ${{github.event_name}} event."
