name: 02 - Workflow Events

on: 
    push:
    pull_request:
    schedule:
        - cron: '*/5 * * * *'
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name:
              run: echo "ive been triggered by a(n) ${{github.event_name}} event."