name: 04- Using Actions

on:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            # - name: Printing Folders
            #   run: ls

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install Deps
              run: npm ci



        # checkout code from repo (workflow must be define inside repo)
        # install depenacies
        # execute automated tests