name: 04- Using Actions

on:
    push:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Printing Folders
              run: ls



        # checkout code from repo (workflow must be define inside repo)
        # install depenacies
        # execute automated tests