name: 12 - Working with Outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            status-build: ${{steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT path
              run: echo "$GITHUB_OUTPUT"
            - name: Bulid
              id: build
              run: echo "status= ${{inputs.build-status}} >> '$GITHUB_OUTPUT'

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{needs.build.outputs.status-build == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying"