name: 17-3 Custom Actions - Docker

on:
    workflow_dispatch:
        inputs:
            url:
                type: choice
                options: 
                    - 'https://www.google.com'
                    - 'www.invalid-sufuejsvfue.com'
                    - 'invalid-aidfghaidgfiazgd'
                required: true
            max-trials:
                description: Maximum trials until action fails
                default: '10'
                required: false

            delays:
                description: Delay in seconds between trials
                default: '5'
                required: false


jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{inputs.url}}
                max-trial: ${{inputs.max-trials}}
                delay: ${{inputs.delays}}

